#pragma once
#include "Objects/Object_3D.h"
#include "Objects/Sphere.h"
#include "Objects/TexturedSphere.h"
#include "Objects/Icosphere.h"
#include "Objects/TexturedIcosphere.h"
#include "Objects/ColorfulIcosphere.h"
#include "Objects/SkyBox.h"
#include "Objects/Text.h"